FROM nginx:alpine-slim
# OCI Label
LABEL org.opencontainers.image.author="bershin"
LABEL org.opencontainers.image.title="Nginx image"
# Cusom label
LABEL maintainer="bershin@gmail.com"
LABEL version="1.0"

COPY index.html /usr/share/nginx/html/