FROM nginx:alpine-slim

COPY app.conf /etc/nginx/conf.d/app.conf
RUN mkdir -p /usr/share/nginx/html/app1
COPY index.html /usr/share/nginx/html/app1/index.html


# Copy the entrypoint script
COPY entrypoint-app1.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# The container will start by executing the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 8080