apiVersion: v1
kind: Pod
metadata:
  name: without-sa
  namespace: wid-ns
spec:
  containers:
  - name: appname
    image: google/cloud-sdk:latest
    command: ["sleep", "infinity"]
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: with-sa
  namespace: wid-ns
spec:
  containers:
  - name: appname
    image: google/cloud-sdk:latest
    command: ["sleep", "infinity"]
  serviceAccount: ksa-wid
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: with-no-node
  namespace: wid-ns
spec:
  containers:
  - name: appname
    image: google/cloud-sdk:latest
    command: ["sleep", "infinity"]
