kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nginx-sts
spec:
  serviceName: nginx-sts
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-pass-hostame
          image: alpine
          command:
            - sh
            - -c
            - echo "POD_NAME:$HOSTNAME" > /usr/share/nginx/html/index.html
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: premium-rwo
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sts
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
  - name: appname
    image: curlimages/curl
    command: ["sleep", "3600"]
---