apiVersion: batch/v1
kind: Job
metadata:
  name: job-completed
spec:
  template:
    spec:
      containers:
      - name: counter
        image: alpine
        command: ['sh', '-c', 'echo Job Completed; sleep 20']
      restartPolicy: Never
  backoffLimit: 4
  completions: 3