apiVersion: v1
kind: Pod
metadata:
  name: app2-pod
spec:
  containers:
  - name: app2
    image: nginx 
    ports:
      - containerPort: 80
    volumeMounts:
    - name: app1-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: app1-volume
    persistentVolumeClaim:
      claimName: app1-pvc
---