version: '3.8'

services:
  service-a:
    build:
      context: ./service_a
    ports:
      - "8001:8000"

  service-b:
    build:
      context: ./service_b
    ports:
      - "8002:8000"

  api-gateway:
    build:
      context: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - service-a
      - service-b
